### PR TITLE
Add example Fetch.get Auto Decode

### PR DESCRIPTION
**Pull request by CraigChamberlain**
I had trouble getting other examples to work so went into the tests.

I'm sorry I haven't read the contribution notes yet, perhaps I should raise an issue first or something.

Hope this helps

C

### CODE REVIEW

**Comment by CraigChamberlain** [comment]
Is this stable enough for me to maybe contribute to the docs?

The case strategy is optional so this may safely be omitted?

The difference I had to implement to compile was really the second generic param which is given the `_` .

`Fetch.get<_, Book >(url)`

**Comment by CraigChamberlain** [comment]
Finally, where is the JS.Promise? It doesn't seem to be in the Json or Fetch namespaces?

Thanks

C

**Comment by MangelMaxime** [comment]
Hello, 

`JS.Promise` is hosted inside `Fable.Core` if I remember correctly.

What you are adding to the documentation is already in it, it's just in the section below called "Type when calling Fetch method". However, the documentation needed to be updated indeed because it's showing the previous version of `Fetch.get`

`return! Fetch.get<Book>(url, isCamelCase = true)` should be `return! Fetch.get<_, Book>(url, caseStrategy = CamelCase)`

In fact, all the documentation needed to be updated to change ` isCamelCase = true` to `caseStrategy = CamelCase`.

In a similar way, I updated the last line of the documentation:

> When using auto coders, you can pass isCamelCase and/or extra arguments in order to control Thoth.Json behaviour. You can learn more about them by reading Thoth.Json documentation.

to

When using auto coders, you can pass `camelCase`

I am closing the PR because I directly fixed the documentation from master. Thank you for pointing out the problems in it

**Comment by CraigChamberlain** [comment]
Yes PR not so helpful as the second pair of eyes. Thanks for fixing
so quickly.

C

**Pull request closed without merging**
