### PR TITLE
WIP: Add tests for unit response

### PR DESCRIPTION
**Pull request by MangelMaxime**
See #5

Waiting for the new release of Thoth.Json

https://github.com/thoth-org/Thoth.Json/pull/28

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello @SCullman 

can you please confirm to me that

```fs
let! res = Fetch.tryGet<unit>("http://localhost:3000/get/unit")
```

Is indeed how you want to request for `unit` in #5?

**Comment by SCullman** [comment]
Hmm. I can't get the tests running as jsonserver requires Phyton 2.7 installed via node-gyp.
So I cannot check whether `http://localhost:3000/get/unit` returns an empty body or something else. 
Is `res?jsonp(null)` the same as ""? IMHO there is no JSON involved here at all.

**Comment by MangelMaxime** [comment]
> returns an empty body or something else.

When using Thoth.Json and Thoth.Json.Net, you don't have to know what it will returns.

If you use another serializer on the server-side, then it's up to the user to either: 

- Configure Thoth.Json to know about its particular format
- Configure his serialiser to generates the expected JSON

It is the same about `Map`, `Set`, etc. representation, not all the serializer use the same format. For example, NewtonSoft (I don't know if this is still the case), use a `$type` property to transport the "type information" over JSON. While others serialise like Thoth, Elm, Chiron don't do that.

I was asking confirmation for `Fetch.tryGet<unit>` part.

**Comment by SCullman** [comment]
Ok, confirmed. 

> When using Thoth.Json and Thoth.Json.Net, you don't have to know what it will returns.   

In [Line 45](https://github.com/thoth-org/Thoth.Fetch/blob/88a3d873497bbc6147c65b66f00fe34a403351df/src/Fetch.fs#L45) Decode.unsafeFromString gets called with response.text() / body. And if this contains an empty string for a unit, Decode.unsafeFromString will currently fail. 

WebApi recognizes that it has to return an empty body, and it doesn't need the help for any serializer/ formatter or converter. Thoth.Json.Net will **never** be involved.

**Comment by SCullman** [comment]
Please replace `res?jsonp(null)` with a `res?sendStatus(204)`  for all \<unit> tests.

**Comment by MangelMaxime** [comment]
ℹ️ You answered while I was writing this message. Because I think it can help to have it written down, I still post it as a reference if we need it later or if someone as a question about all that `unit` stuff*. 

Just because, we speak a lot about this issue I want to say that I am not trying to say that I am right about my idea for `unit` support and don't want to hear others approach. 

I think we both want to have proper support for it because it's valuable and the proof is that you need it and some people asked for it in the past too.

I will try to explain what I understand from my view.

For me, there are two things that we are discussing:

* **Case 1**: Handling `unit` inside of the JSON representation
* **Case 2**: Handling request that returns no body/nothing and interprets them as `unit`

### **Case 1**: Handling `unit` inside of the JSON representation

This case is about handling `unit` inside of Thoth.Json. This library works on top of JSON and so can only work with valid JSON representation.

The reason for that is if I had support to `unit` in it then I have to make sure that all theses cases (there are probably more)

*Having `unit` as the direct result*

```fs
let res = Decode.Auto.fromString<unit>(json)
```

*Having `unit` inside a record property*

```fs
let res = Decode.Auto.fromString<{| UnitProperty : unit |}>(json)
```

*Having `unit` inside a DU case*

```fs
type SomeDU =
    | UnitCase of unit

let res = Decode.Auto.fromString<SomeDU>(json)
```

Why do I need to make sure that all three case works? Because I can't expect the user to know that he should not use `unit` in some particular cases. So same as `int`, `bool`, `MyCustomType`, etc. can be used in all theses case, then `unit` is treated the same.

I agree that *Having `unit` inside a record property* and *Having `unit` inside a DU case* are not something that should happen it still can. For example, for the *Having `unit` inside a DU case* it can occur when using `Elmish.Debugger` because perhaps the user has a `Cmd|Msg` like that:

```fs
type Msg =
    | OnComplete of unit
    | OnFailed of exn
    | TriggerOperation

let myAsyncOperation () =
    promise {
        do! longRunningOperation()
        return ()
    }    

let update (msg : Msg) (model : Model) =
    match msg with
    | TriggerOperation ->
        model
        , Cmd.OfPromise.either myAsyncOperation () OnComplete OnFailed        
```

* **Case 2**: Handling request that returns no body/nothing and interprets them as `unit`

This case is about handling `unit` inside the communication layer (for example, Thoth.Fetch can be one, or perhaps your library that is using it underneath).

In this case, what we want is the library to check if there are a body or no.

- If no body found, then it a `unit` returns
- If a body is found, then it applies the decoder on it

> WebApi recognises that it has to return an empty body, and it doesn't need the help for any serializer/ formatter or converter. Thoth.Json.Net will **never** be involved.

Ok, sorry I didn't know that. Then, this means that handling `unit` inside Thoth.Json can't solve this problem, and you are right to ask for handling the no body case. 

And so, we have to do it in this library.

In order to add support for it, we will check for the status **code 204** (as you asked) and also we can check the body length. All that, with a check against `'Response` type to see if it's `unit` should allow us to handle `unit` in a safe manner in this library.

**Comment by SCullman** [comment]
I am asking mostly for Case 2 :-)

However, we cannot rely on the status code of 204. This was just my proposal for the test.
At least code of 200/202/205 are also possible and still valid.

**Comment by MangelMaxime** [comment]
> I am asking mostly for Case 2 :-)

That's what I understand now after all the discussions :) Better late than never ^^

Ok, so perhaps it's just better to check the `body`  presence and the `'Response` type and not care about the status code.

And I guess I will also need to add proper error handling to `Thoth.Fetch` because right now I am not sure what it's will do for error 500 for example. (Spoiler, just crash or do nothing I guess)

[Source](https://github.com/thoth-org/Thoth.Fetch/blob/master/src/Fetch.fs#L41-L42)

**Comment by MangelMaxime** [comment]
Ok, I made a quick test in the Fable REPL and it should be possible to isolate the `unit` calls without using reflection neither `unbox` hacks.

**Code**

```fs
module Thoth.RandomUser

open Fable.Core
open Fable.Core.JsInterop

type Test =
    static member fetchAs<'Response>(url : string,
                                     [<Inject>] ?responseResolver: ITypeResolver<'Response>) : 'Response =
        printfn "This is the generic version of the API"
        // This should be Decode.fromString ...
        // I just used `unbox` to make a minimal repro
        unbox "" 


    static member fetchAs(url : string) : unit =
        printfn "This is the unit version of the API"
        ()

let maxime = Test.fetchAs("")
let maxime2 = Test.fetchAs<int>("")
```

**Console output**

```
This is the unit version of the API
This is the generic version of the API
```

**Comment by SCullman** [comment]
Without the second member, following code would be the same:
```fsharp
let maxime2 = Test.fetchAs<int>("")
let maxime3: int = Test.fetchAs("")
```

Isn't ` static member fetchAs(url : string) : unit` just `fetch`?

```fsharp
    static member fetch(url : string) : unit =
        printfn "This is the unit version of the API"
        // () not needed. unit is always just a side effect like printfn, isn't it?
```
That's what I meant [here ](https://github.com/thoth-org/Thoth.Json/pull/25#issuecomment-536965457). A clean api with `fetch/fetchAs`, `get/getAs`, `post/postAs`..

**Comment by MangelMaxime** [comment]
> Isn't ` static member fetchAs(url : string) : unit` just `fetch`?

Not really, because `fetch` from the `Fable.Fetch` API expects you to handle the `Response` while `fetchAs(url : string) : unit` explicitly say I am expecting `unit` as a result and that's the library job to check if `Response` is indeed representing `unit` or not.

> ```fsharp
>     static member fetch(url : string) : unit =
>         printfn "This is the unit version of the API"
>         // () not needed. unit is always just a side effect like printfn, isn't it?
> ```

Yes, in this case `()` was not needed but in the "real" library code we will not use `printfn` but something like that:

```fs
    static member fetchAs(url : string,
                          ?properties : RequestProperties list) : JS.Promise<unit> =
        promise {
            let properties = defaultArg properties []
            // TODO: Rewrite our own version of `Fetch.fetch` to give better error
            // ATM, when an error occured we are loosing information like status code, etc.
            let! response = Fetch.fetch url properties
            let! body = response.text()
            if String.IsNullOrEmpty body then
                return ()
            else
                failwith "No body expected for this request. If you expect a body to decode, please prove a decoder"
        }
```

> A clean api with `fetch/fetchAs`, `get/getAs`, `post/postAs`..

If the compiler can make the distinction between `unit` or `'Response` type of the method I don't think it needs to ask the user to choose between 2 methods.

In the time of `Fable.PowerPack` we had 2 versions `fetch` and `fetchAs` and people were always confused about them.

I will release a beta version when the tests pass to get feedback from the users.

**Comment by MangelMaxime** [comment]
ℹ️ In case you saw my previous comment, I deleted my previous comment after thinking again about it.

> ```fsharp
>     static member fetch(url : string) : unit =
>         printfn "This is the unit version of the API"
>         // () not needed. unit is always just a side effect like printfn, isn't it?
> ```

Yes, in this case `()` was not needed but in the "real" library code we will not use `printfn` but something like that:

> That's what I meant [here ](https://github.com/thoth-org/Thoth.Json/pull/25#issuecomment-536965457). A clean api with `fetch/fetchAs`, `get/getAs`, `post/postAs`..

Ok so if I understand correctly you propose to have 

- `unit` support by checking if `response.body = ""` via:
    - `get`
    - `post`
    - `put`
    - `patch`
    - etc.
- `'Response` support by expecting a JSON value and decoding it via:
    - `getAs`
    - `postAs`
    - `putAs`
    - `patchAs`
    - etc.

Am I correct?

At first, I wanted to make everything using a unified name for the methods but then I stumble onto a subtle case.

```fs
// This is checking if `reponse.body = ""`
let! res : unit = Fable.get("")    

// This is expecting a JSON and check if this JSON represents `unit`
let! res = Fable.get<unit>("")    
``` 

And I think, this situation can be confusing.

**Comment by SCullman** [comment]
Yes, you are correct.  
The `..As` suffix would indicate that the function expects data encoded with JSON. 

```fsharp
// This is completely ignoring the body
let! res : unit = Fable.get("")    

// This indicates that no body is expected as empty.
// The body is never JSON.
// If it is JSON, we should either throw an exception or ignore it
// like  |> ignore
let! res = Fable.get<unit>("")    
```
IMHO, _in that case_ `getAs<unit>` should even not be supported as "" is not valid Json.

**Comment by MangelMaxime** [comment]
> Yes, you are correct.
> The `..As` suffix would indicate that the function expects data encoded with JSON.

Cool, I am working on it then.

> IMHO, in that case getAs<unit> should even not be supported as "" is not valid Json.

Here that's Thoth.Json job to decide what is `unit` or not as a JSON value 😉, but we can have a check for `response.body = ""` before calling Thoth.Json to have one more "chance" to capture `unit`.

**Comment by SCullman** [comment]
@MangelMaxime, I woke up this morning thinking maybe the answer is as simple as [this](https://fable.io/repl/#?code=LYewJgrgNgpgBAFQBYgC5IHQCUCGA7MEYAVQGcYAnAKCpAAcY84AxHAI1gwGEQKZaGTVhxjdeogFKkAknlSV6NVAE8GiGKVRwAvFTj64mnKgCWAYzjAYwNpTgAzGKjNIAgqQA8Aciwa6IPHIAPj0DMPCDAAo4CAooOAAuQ1QKEzwAcwAaUIjcgwBtD1kAKxgzVCCAXTgAfj5SECgAN0ok6QRVGF8G5spvbv9AmCCASkS4Hz8A8h0c8Lmwk3s4esaWigwANRwoCFFutZgOhkiRjGZoKAA5HCsdOBUGMBh7EHsPCDwTCvPLm7uFgZ0Iw4IDwnRUnJ7EwAETMJwuOAmUgPPjGGBgOA4QwmZ5wF6OcqZJHpPC8NLpOCuK4ATRWUyGMLBYU+bBAAA84KdmTAoORmQYIWlUNC4DDkMj6ahYoEHkh4E0dnsYqQKXAACJlcCiewUIgAZRSaowJqZeQMrI5cAAjKCqLAtMKvPcEBpUBhHM43J5hUFIjCYSN7U4kXIvF4EsKXW6PQjvf7A8GtJ9vs7tOpNLGve4Pl8Kgmgw6Ynnw+MU1p067M56XO4C1Qq+6a-GAyMgA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLswooOgBzLlYJPl5tcTo0MK8fXXEAdxiwEFYARgAGHPEQJGDwVjNcmGtPb18rJScXeEQVSFg4IA&css=Q)?
```fsharp
module Thoth.RandomUser

open Fable.Core
open Fable.Core.JsInterop

type Test =
    static member fetchAs<'Response>
                ( url : string,
                  [<Inject>] ?resolver: ITypeResolver<'Response>) : 'Response =
        
        if resolver.Value.ResolveType().FullName = typedefof<unit>.FullName 
        then 
           printfn "Fetch is treated a side effect, ignoring ANY response"
           unbox ()
        else
           printfn "This returns the value using Decode.fromString ..."
           unbox 1 

let int' = Test.fetchAs<int>("")
let int'':int = Test.fetchAs("")
let unit' = Test.fetchAs<unit>("")
let unit'' : unit = Test.fetchAs("")
Test.fetchAs("")
``` 
=>
```
This returns the value using Decode.fromString ...
This returns the value using Decode.fromString ...
Fetch is treated a side effect, ignoring ANY response
Fetch is treated a side effect, ignoring ANY response
Fetch is treated a side effect, ignoring ANY response
```

**Comment by MangelMaxime** [comment]
I think #10 was choose in favor of this PR and I forgot to close this one.

**Pull request closed without merging**
